version: "3"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3308:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails  # ホストのカレントディレクトリをコンテナの /rails にマウント
      - ./vendor/bundle:/rails/vendor/bundle  # bundler のキャッシュを共有
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  mysql-data:
